apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: problem-volume
  namespace: mainnet-shots-2
spec:
  storageClassName: ebs-sc
  dataSource:
    name: 2021-11-17-18-29-54-node-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi
