apiVersion: v1
kind: Pod
metadata:
  name: snapshot-scheduler
  namespace: mainnet-shots
spec:
  serviceAccountName: snapshot-maker-sa
  containers:
    - name: snapshot-scheduler
      image: 082993323195.dkr.ecr.us-east-2.amazonaws.com/snapshot-scheduler:latest
      env:
        - name: NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: snapshot-configmap
              key: NAMESPACE
  restartPolicy: Never
