apiVersion: v1
kind: Pod
metadata:
  name: snapshot-scheduler
  namespace: mainnet-shots-2
spec:
      serviceAccountName: snapshot-maker-sa
      containers:
        - name: zip-and-upload
          image: 082993323195.dkr.ecr.us-east-2.amazonaws.com/zip-and-upload:latest
          volumeMounts:
            - mountPath: /var/tezos
              name: persistent-storage
              readOnly: true
            - mountPath: /snapshot-cache-volume
              name: snapshot-cache-volume
            - mountPath: /rolling-tarball-restore
              name: rolling-tarball-restore
          env:
            - name: NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: snapshot-configmap
                  key: NAMESPACE
      restartPolicy: Never
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: problem-volume
