apiVersion: v1
kind: Deployment
metadata:
  name: snapshot-scheduler
replicas: 1
selector:
  matchLabels:
    app: snapshot-scheduler
template:
  metadata:
    labels:
      app: snapshot-scheduler
  spec:
    serviceAccountName: {{ .Values.service_account }}
    containers:
      - name: snapshot-scheduler
        image: {{ .Values.tezos_k8s_images.snapshot_maker }}
        env:
          - name: NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: snapshot-configmap
                key: NAMESPACE
    restartPolicy: Never

apiVersion: v1
data:
  NAMESPACE: {{ .Values.namespace }}
  VOLUME_SNAPSHOT_CLASS_NAME: test-snapclass
kind: ConfigMap