apiVersion: v1
kind: Pod
metadata:
  name: snapshot-scheduler
  namespace: {{ .Values.namespace }}
spec:
  serviceAccountName: {{ .Values.service_account }}
  containers:
    - name: snapshot-scheduler
      image: 082993323195.dkr.ecr.us-east-2.amazonaws.com/snapshot-scheduler:latest
      env:
        - name: NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: snapshot-configmap
              key: NAMESPACE
  restartPolicy: Never

apiVersion: v1
data:
  NAMESPACE: {{ .Values.namespace }}
  VOLUME_SNAPSHOT_CLASS_NAME: test-snapclass
kind: ConfigMap