apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mainnet-shots
  name: modify-volumesnapshots
rules:
  - apiGroups: ["snapshot.storage.k8s.io", batch, ""]
    resources:
      - volumesnapshots
      - jobs
      - persistentvolumeclaims
      - configmaps
      - pods
    verbs:
      - get
      - list
      - delete
      - create
      - patch
